### INDEXING AND SLICING

In [6]:
import numpy as np
x = np.array([[1., 2.], [np.nan, 3.], [np.nan, np.nan]])
x[~np.isnan(x)] 
x

array([[ 1.,  2.],
       [nan,  3.],
       [nan, nan]])

In [7]:
x = np.arange(35).reshape(5, 7)
b = x > 20
x

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [9]:
x[:3,3]

array([ 3, 10, 17])

Boolean array/mask

In [18]:
b[:, 5]

array([False, False, False,  True,  True])

prints row based on the True value in the index of a boolean array


In [22]:
x[[False, False, True,  True,  True]]


array([[14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [27]:
x.sum(-1) # or x.sum(axis = 1)
# -1 is equal to axis = 1, means sum along the column


array([ 21,  70, 119, 168, 217])

In [29]:
x = np.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]])
rows = (x.sum(-1) % 2) == 0
x[rows]
columns = [0, 2]
x[np.ix_(rows, columns)]

array([[ 3,  5],
       [ 9, 11]])

In [30]:
# indexing in grid way
x = np.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]])
rows = np.array([[0, 0],
                 [3, 3]], dtype=np.intp)
columns = np.array([[0, 2],
                    [0, 2]], dtype=np.intp)
x[rows, columns]

array([[ 0,  2],
       [ 9, 11]])

other way using a grid

In [31]:
rows = np.array([0, 3], dtype=np.intp)
columns = np.array([0, 2], dtype=np.intp)
rows[:, np.newaxis]
x[rows[:, np.newaxis], columns]

array([[ 0,  2],
       [ 9, 11]])